server:
  port: 9004
spring:
  application:
    name: service-search
  datasource:
    driver-class-name: org.postgresql.Driver
  cloud:
    nacos:
      discovery:
        server-addr:
      config:
        server-addr:
        file-extension: yaml
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
